### ISSUE TITLE
Menu input

### ISSUE THREAD

**Issue by rt-2** [romgerman/GTAVMenuVueHtml#5]
Hi,
I am implementing inputs.
I'm not sure if I should make a fork or pull it here later.
Its not default from GTA V and the design is not perfect.
Let me know what you think.
rt-2

**Comment by romgerman** [comment]
That's up to you.

**Comment by rt-2** [comment]
Well right now I am still testing them, by the way, is there anything in your script that plays with the cursor, I am having trouble with the cursor disappearing when trying to test the new inputs?
Thank you!
rt-2

**Comment by romgerman** [comment]
> is there anything in your script that player with the cursor

I guess not.

**Comment by rt-2** [comment]
Plays* sorry..
