### ISSUE TITLE
Strange behavior for submenus with more than 8 elements

### ISSUE THREAD

**Issue by rt-2** [romgerman/GTAVMenuVueHtml#6]
Hi,
I have noticed that when I use a menu with more than the normal displayed item it have weird effects.
Steps to reproduce:
   1 - Use your example, but in `submenuInfo` copy paste one of the `MenuItem` so that there is about 15-20 elements;
   2 - Use the example, and in the submenu, you will see that all the elements are displayed;
   3 - If you scroll down the menu fixes itself, then scrolling down seems to work fine;
   4 - Scrolling up with show some wired effects again;
Thank you very much,
rt-2

**Comment by romgerman** [comment]
https://github.com/romgerman/GTAVMenuVueHtml/commit/851f4fa403e5612f968d7decc9e5d7a8757e3575
