### ISSUE TITLE
Item selection should be on second click

### ISSUE THREAD

**Issue by rt-2** [romgerman/GTAVMenuVueHtml#7]
In the original game, a menu item is only executed at the second click.
First the item get highlighted, then if clicked again it executes.
I think it would be easy for you to implement that if I'm not wrong.
rt-2

**Comment by romgerman** [comment]
https://github.com/romgerman/GTAVMenuVueHtml/commit/851f4fa403e5612f968d7decc9e5d7a8757e3575

**Comment by rt-2** [comment]
Thanks a lot
